upgrade for ha pipeline

diff --git a/ci/scripts/build-deploy-rc-artifact b/ci/scripts/build-deploy-rc-artifact
--- a/ci/scripts/build-deploy-rc-artifact
+++ b/ci/scripts/build-deploy-rc-artifact
@@ -14,6 +14,11 @@ if [ -z "$ARTIFACTORY_LICENSE" ]; then
   exit 30
 fi
 
+if [ -z "$ARTIFACTORY1_LICENSE" ]; then
+  echo "missing artifactory license for second node"
+  exit 30
+fi
+
 cd artifactory-bosh-release-master
 
 bosh -n target ${BOSH_TARGET}
